name: Commitlint

on:
    push:

jobs:
    commitlint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install dependencies
              run: npm ci
            - name: Lint commit messages
              env:
                  FROM: ${{ github.event.before }}
                  TO: ${{ github.event.after }}
              run: npx commitlint --from=$FROM --to=$TO
