name: Commitlint

on:
    push:

jobs:
    commitlint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Install dependencies
              run: npm ci
            - name: Lint commit messages
              run: npx commitlint --from=${GITHUB_SHA}^ --to=${GITHUB_SHA}
