name: CI

on: pull_request_target

jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: ${{ github.head_ref }}
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - name: Install deps
              run: npm ci
            - name: Unit tests
              run: npm run test-ci
            - name: e2e tests
              run: npm run e2e
            - name: Lint tests
              run: npm run lint
