name: Release
on:
    push:
        tags:
            - 'v*'
jobs:
    release:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code!
              uses: actions/checkout@v3
            - name: Generate changelog
              id: changelog
              uses: metcalfc/changelog-generator@v4.1.0
              with:
                  myToken: ${{ secrets.GITHUB_TOKEN }}
            - name: Create Issue From File
              uses: JasonEtco/create-an-issue@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BODY: ${{ steps.changelog.outputs.changelog }}
