name: Release
on:
    push:
        tags:
            - 'v[0-9]+'
jobs:
    release:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code!
              uses: actions/checkout@v3
            - name: Create changelog text
              id: changelog
              uses: loopwerk/tag-changelog@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Create Issue From File!!!!!
              uses: JasonEtco/create-an-issue@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BODY: ${{ steps.changelog.outputs.changelog }}
