name: Release
on:
    push:
        tags:
            - 'v[0-9]+'
jobs:
    release:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code!
              uses: actions/checkout@v3
            - name: Create changelog text
              id: changelog
              uses: loopwerk/tag-changelog@v1
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
            - name: Create Issue From File!!!!!
              uses: JasonEtco/create-an-issue@v2
              id: createIssue
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BODY: ${{ steps.changelog.outputs.changelog }}
                  VERSION: ${{ github.ref_name }}
                  NAME: ${{ github.actor }}
              with:
                  update_existing: true
                  search_existing: all
            - name: Install deps
              run: npm ci
            - name: Unit tests
              run: npm run test-ci
            - name: Upload Artifact
              uses: actions/upload-artifact@v3
              with:
                  name: unit-test-report
                  path: test-report.html
            - uses: actions/download-artifact@v3
              id: download1
              with:
                  name: unit-test-report
                  path: test-report.html
            - name: Lint tests
              run: npm run lint
            - name: Build
              run: npm run build
            - name: Deploy!
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                  folder: build
            - name: Close Issue
              uses: peter-evans/close-issue@v3
              with:
                  issue-number: ${{ steps.createIssue.outputs.number }}
                  comment: Успешный деплой на gh-pages завершен! ${{steps.download1.outputs}}
