name: Release
on:
    push:
        tags:
            - 'v[0-9]+'
jobs:
    release:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code!
              uses: actions/checkout@v3
            - name: Conventional Changelog Action
              id: changelog
              uses: TriPSs/conventional-changelog-action@v3
              with:
                  github-token: ${{ secrets.github_token }}
                  skip-commit: 'true'
            - name: Create Issue From File!!!
              uses: JasonEtco/create-an-issue@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BODY: ${{ steps.changelog.outputs.changelog }}
