name: Release
on:
    push:
        tags:
            - 'v*'
jobs:
    release:
        permissions: write-all
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code!
              uses: actions/checkout@v3
            - name: '✏️ Generate release changelog!'
              id: changelog
              uses: heinrichreimer/github-changelog-generator-action@v2.3
              with:
                  token: ${{ secrets.GITHUB_TOKEN }}
                  onlyLastTag: true
            - name: Create Issue From File
              uses: JasonEtco/create-an-issue@v2
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  BODY: ${{ steps.changelog.outputs.changelog }}
